export const CAST_MEMBER_LIST_REQUEST = "CAST_MEMBER_LIST_REQUEST";
export const CAST_MEMBER_LIST_SUCCESS = "CAST_MEMBER_LIST_SUCCESS";
export const CAST_MEMBER_LIST_FAIL = "CAST_MEMBER_LIST_FAIL";
export const CAST_MEMBER_LIST_UPDATE_REQUEST =
  "CAST_MEMBER_LIST_UPDATE_REQUEST";
export const CAST_MEMBER_LIST_RESET = "CAST_MEMBER_LIST_RESET";

export const CAST_MEMBER_DETAILS_REQUEST = "CAST_MEMBER_DETAILS_REQUEST";
export const CAST_MEMBER_DETAILS_SUCCESS = "CAST_MEMBER_DETAILS_SUCCESS";
export const CAST_MEMBER_DETAILS_FAIL = "CAST_MEMBER_DETAILS_FAIL";

export const CAST_MEMBER_CREATE_REQUEST = "CAST_MEMBER_CREATE_REQUEST";
export const CAST_MEMBER_CREATE_SUCCESS = "CAST_MEMBER_CREATE_SUCCESS";
export const CAST_MEMBER_CREATE_FAIL = "CAST_MEMBER_CREATE_FAIL";
export const CAST_MEMBER_CREATE_RESET = "CAST_MEMBER_CREATE_RESET";
