export const CAST_MEMBER_LIST_REQUEST = "CAST_MEMBER_LIST_REQUEST";
export const CAST_MEMBER_LIST_SUCCESS = "CAST_MEMBER_LIST_SUCCESS";
export const CAST_MEMBER_LIST_FAIL = "CAST_MEMBER_LIST_FAIL";
export const CAST_MEMBER_LIST_UPDATE_REQUEST =
  "CAST_MEMBER_LIST_UPDATE_REQUEST";
