export const COMPANY_LIST_REQUEST = "COMPANY_LIST_REQUEST";
export const COMPANY_LIST_SUCCESS = "COMPANY_LIST_SUCCESS";
export const COMPANY_LIST_FAIL = "COMPANY_LIST_FAIL";
export const COMPANY_LIST_UPDATE_REQUEST = "COMPANY_LIST_UPDATE_REQUEST";
export const COMPANY_LIST_RESET = "COMPANY_LIST_RESET";

export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";
export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS";
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL";

export const COMPANY_ADD_REVIEW_REQUEST = "COMPANY_ADD_REVIEW_REQUEST";
export const COMPANY_ADD_REVIEW_SUCCESS = "COMPANY_ADD_REVIEW_SUCCESS";
export const COMPANY_ADD_REVIEW_FAIL = "COMPANY_ADD_REVIEW_FAIL";
export const COMPANY_ADD_REVIEW_RESET = "COMPANY_ADD_REVIEW_RESET";

export const COMPANY_ADD_IMAGE_REQUEST = "COMPANY_ADD_IMAGE_REQUEST";
export const COMPANY_ADD_IMAGE_SUCCESS = "COMPANY_ADD_IMAGE_SUCCESS";
export const COMPANY_ADD_IMAGE_FAIL = "COMPANY_ADD_IMAGE_FAIL";
export const COMPANY_ADD_IMAGE_RESET = "COMPANY_ADD_IMAGE_RESET";

export const COMPANY_CREATE_REQUEST = "COMPANY_CREATE_REQUEST";
export const COMPANY_CREATE_SUCCESS = "COMPANY_CREATE_SUCCESS";
export const COMPANY_CREATE_FAIL = "COMPANY_CREATE_FAIL";
export const COMPANY_CREATE_RESET = "COMPANY_CREATE_RESET";

export const COMPANY_MY_REVIEWS_REQUEST = "COMPANY_MY_REVIEWS_REQUEST";
export const COMPANY_MY_REVIEWS_SUCCESS = "COMPANY_MY_REVIEWS_SUCCESS";
export const COMPANY_MY_REVIEWS_FAIL = "COMPANY_MY_REVIEWS_FAIL";
export const COMPANY_MY_REVIEWS_RESET = "COMPANY_MY_REVIEWS_RESET";

export const COMPANY_USER_REVIEWS_REQUEST = "COMPANY_USER_REVIEWS_REQUEST";
export const COMPANY_USER_REVIEWS_SUCCESS = "COMPANY_USER_REVIEWS_SUCCESS";
export const COMPANY_USER_REVIEWS_FAIL = "COMPANY_USER_REVIEWS_FAIL";
export const COMPANY_USER_REVIEWS_RESET = "COMPANY_USER_REVIEWS_RESET";
