export const SHOW_LIST_REQUEST = "SHOW_LIST_REQUEST";
export const SHOW_LIST_SUCCESS = "SHOW_LIST_SUCCESS";
export const SHOW_LIST_FAIL = "SHOW_LIST_FAIL";
export const SHOW_LIST_UPDATE_REQUEST = "SHOW_LIST_UPDATE_REQUEST";

export const SHOW_DETAILS_REQUEST = "SHOW_DETAILS_REQUEST";
export const SHOW_DETAILS_SUCCESS = "SHOW_DETAILS_SUCCESS";
export const SHOW_DETAILS_FAIL = "SHOW_DETAILS_FAIL";

export const SHOW_CREATE_REQUEST = "SHOW_CREATE_REQUEST";
export const SHOW_CREATE_SUCCESS = "SHOW_CREATE_SUCCESS";
export const SHOW_CREATE_FAIL = "SHOW_CREATE_FAIL";
export const SHOW_CREATE_RESET = "SHOW_CREATE_RESET";

export const SHOW_UPDATE_REQUEST = "SHOW_UPDATE_REQUEST";
export const SHOW_UPDATE_SUCCESS = "SHOW_UPDATE_SUCCESS";
export const SHOW_UPDATE_FAIL = "SHOW_UPDATE_FAIL";
export const SHOW_UPDATE_RESET = "SHOW_UPDATE_RESET";

export const SHOW_ADD_REVIEW_REQUEST = "SHOW_ADD_REVIEW_REQUEST";
export const SHOW_ADD_REVIEW_SUCCESS = "SHOW_ADD_REVIEW_SUCCESS";
export const SHOW_ADD_REVIEW_FAIL = "SHOW_ADD_REVIEW_FAIL";
export const SHOW_ADD_REVIEW_RESET = "SHOW_ADD_REVIEW_RESET";

export const SHOW_VENUE_PERFORMANCES_REQUEST =
  "SHOW_VENUE_PERFORMANCES_REQUEST";
export const SHOW_VENUE_PERFORMANCES_SUCCESS =
  "SHOW_VENUE_PERFORMANCES_SUCCESS";
export const SHOW_VENUE_PERFORMANCES_FAIL = "SHOW_VENUE_PERFORMANCES_FAIL";
export const SHOW_VENUE_PERFORMANCES_RESET = "SHOW_VENUE_PERFORMANCES_RESET";

export const SHOW_ADD_PERFORMANCE_REQUEST = "SHOW_ADD_PERFORMANCE_REQUEST";
export const SHOW_ADD_PERFORMANCE_SUCCESS = "SHOW_ADD_PERFORMANCES_SUCCESS";
export const SHOW_ADD_PERFORMANCE_FAIL = "SHOW_ADD_PERFORMANCE_FAIL";
export const SHOW_ADD_PERFORMANCE_RESET = "SHOW_ADD_PERFORMANCE_RESET";

export const SHOW_ADD_IMAGE_REQUEST = "SHOW_ADD_IMAGE_REQUEST";
export const SHOW_ADD_IMAGE_SUCCESS = "SHOW_ADD_IMAGE_SUCCESS";
export const SHOW_ADD_IMAGE_FAIL = "SHOW_ADD_IMAGE_FAIL";
export const SHOW_ADD_IMAGE_RESET = "SHOW_ADD_IMAGE_RESET";

export const SHOW_COMPANY_LIST_REQUEST = "SHOW_COMPANY_LIST_REQUEST";
export const SHOW_COMPANY_LIST_SUCCESS = "SHOW_COMPANY_LIST_SUCCESS";
export const SHOW_COMPANY_LIST_FAIL = "SHOW_COMPANY_LIST_FAIL";
export const SHOW_COMPANY_LIST_RESET = "SHOW_COMPANY_LIST_RESET";

export const SHOW_ADD_ROLE_REQUEST = "SHOW_ADD_ROLE_REQUEST";
export const SHOW_ADD_ROLE_SUCCESS = "SHOW_ADD_ROLE_SUCCESS";
export const SHOW_ADD_ROLE_FAIL = "SHOW_ADD_ROLE_FAIL";
export const SHOW_ADD_ROLE_RESET = "SHOW_ADD_ROLE_RESET";

export const SHOW_MY_REVIEWS_REQUEST = "SHOW_MY_REVIEWS_REQUEST";
export const SHOW_MY_REVIEWS_SUCCESS = "SHOW_MY_REVIEWS_SUCCESS";
export const SHOW_MY_REVIEWS_FAIL = "SHOW_MY_REVIEWS_FAIL";
export const SHOW_MY_REVIEWS_RESET = "SHOW_MY_REVIEWS_RESET";

export const SHOW_REVIEW_DETAILS_REQUEST = "SHOW_REVIEW_DETAILS_REQUEST";
export const SHOW_REVIEW_DETAILS_SUCCESS = "SHOW_REVIEW_DETAILS_SUCCESS";
export const SHOW_REVIEW_DETAILS_FAIL = "SHOW_REVIEW_DETAILS_FAIL";
export const SHOW_REVIEW_DETAILS_RESET = "SHOW_REVIEW_DETAILS_RESET";

export const SHOW_ADD_REVIEW_COMMENT_REQUEST =
  "SHOW_ADD_REVIEW_COMMENT_REQUEST";
export const SHOW_ADD_REVIEW_COMMENT_SUCCESS =
  "SHOW_ADD_REVIEW_COMMENT_SUCCESS";
export const SHOW_ADD_REVIEW_COMMENT_FAIL = "SHOW_ADD_REVIEW_COMMENT_FAIL";
export const SHOW_ADD_REVIEW_COMMENT_RESET = "SHOW_ADD_REVIEW_COMMENT_RESET";

export const SHOW_UPDATE_REVIEW_REQUEST = "SHOW_UPDATE_REVIEW_REQUEST";
export const SHOW_UPDATE_REVIEW_SUCCESS = "SHOW_UPDATE_REVIEW_SUCCESS";
export const SHOW_UPDATE_REVIEW_FAIL = "SHOW_UPDATE_REVIEW_FAIL";
export const SHOW_UPDATE_REVIEW_RESET = "SHOW_UPDATE_REVIEW_RESET";

export const SHOW_UPDATE_REVIEW_COMMENT_REQUEST =
  "SHOW_UPDATE_REVIEW_COMMENT_REQUEST";
export const SHOW_UPDATE_REVIEW_COMMENT_SUCCESS =
  "SHOW_UPDATE_REVIEW_COMMENT_SUCCESS";
export const SHOW_UPDATE_REVIEW_COMMENT_FAIL =
  "SHOW_UPDATE_REVIEW_COMMENT_FAIL";
export const SHOW_UPDATE_REVIEW_COMMENT_RESET =
  "SHOW_UPDATE_REVIEW_COMMENT_RESET";

export const SHOW_DELETE_REVIEW_REQUEST = "SHOW_DELETE_REVIEW_REQUEST";
export const SHOW_DELETE_REVIEW_SUCCESS = "SHOW_DELETE_REVIEW_SUCCESS";
export const SHOW_DELETE_REVIEW_FAIL = "SHOW_DELETE_REVIEW_FAIL";
export const SHOW_DELETE_REVIEW_RESET = "SHOW_DELETE_REVIEW_RESET";

export const SHOW_DELETE_REVIEW_COMMENT_REQUEST =
  "SHOW_DELETE_REVIEW_COMMENT_REQUEST";
export const SHOW_DELETE_REVIEW_COMMENT_SUCCESS =
  "SHOW_DELETE_REVIEW_COMMENT_SUCCESS";
export const SHOW_DELETE_REVIEW_COMMENT_FAIL =
  "SHOW_DELETE_REVIEW_COMMENT_FAIL";
export const SHOW_DELETE_REVIEW_COMMENT_RESET =
  "SHOW_DELETE_REVIEW_COMMENT_RESET";

export const SHOW_USER_REVIEWS_REQUEST = "SHOW_USER_REVIEWS_REQUEST";
export const SHOW_USER_REVIEWS_SUCCESS = "SHOW_USER_REVIEWS_SUCCESS";
export const SHOW_USER_REVIEWS_FAIL = "SHOW_USER_REVIEWS_FAIL";
export const SHOW_USER_REVIEWS_RESET = "SHOW_USER_REVIEWS_RESET";

export const SHOW_CASTMEMBER_ROLES_REQUEST = "SHOW_CASTMEMBER_ROLES_REQUEST";
export const SHOW_CASTMEMBER_ROLES_SUCCESS = "SHOW_CASTMEMBER_ROLES_SUCCESS";
export const SHOW_CASTMEMBER_ROLES_FAIL = "SHOW_CASTMEMBER_ROLES_FAIL";
export const SHOW_CASTMEMBER_ROLES_RESET = "SHOW_CASTMEMBER_ROLES_RESET";

export const SHOW_ADD_VIEWER_REQUEST = "SHOW_ADD_VIEWER_REQUEST";
export const SHOW_ADD_VIEWER_SUCCESS = "SHOW_ADD_VIEWER_SUCCESS";
export const SHOW_ADD_VIEWER_FAIL = "SHOW_ADD_VIEWER_FAIL";
export const SHOW_ADD_VIEWER_RESET = "SHOW_ADD_VIEWER_RESET";

export const SHOW_MY_WATCHLIST_REQUEST = "SHOW_MY_WATCHLIST_REQUEST";
export const SHOW_MY_WATCHLIST_SUCCESS = "SHOW_MY_WATCHLIST_SUCCESS";
export const SHOW_MY_WATCHLIST_FAIL = "SHOW_MY_WATCHLIST_FAIL";
export const SHOW_MY_WATCHLIST_RESET = "SHOW_MY_WATCHLIST_RESET";

export const SHOW_DELETE_VIEWER_REQUEST = "SHOW_DELETE_VIEWER_REQUEST";
export const SHOW_DELETE_VIEWER_SUCCESS = "SHOW_DELETE_VIEWER_SUCCESS";
export const SHOW_DELETE_VIEWER_FAIL = "SHOW_DELETE_VIEWER_FAIL";
export const SHOW_DELETE_VIEWER_RESET = "SHOW_DELETE_VIEWER_RESET";
