export const SHOW_LIST_REQUEST = "SHOW_LIST_REQUEST";
export const SHOW_LIST_SUCCESS = "SHOW_LIST_SUCCESS";
export const SHOW_LIST_FAIL = "SHOW_LIST_FAIL";
export const SHOW_LIST_UPDATE_REQUEST = "SHOW_LIST_UPDATE_REQUEST";

export const SHOW_DETAILS_REQUEST = "SHOW_DETAILS_REQUEST";
export const SHOW_DETAILS_SUCCESS = "SHOW_DETAILS_SUCCESS";
export const SHOW_DETAILS_FAIL = "SHOW_DETAILS_FAIL";

export const SHOW_CREATE_REQUEST = "SHOW_CREATE_REQUEST";
export const SHOW_CREATE_SUCCESS = "SHOW_CREATE_SUCCESS";
export const SHOW_CREATE_FAIL = "SHOW_CREATE_FAIL";
export const SHOW_CREATE_RESET = "SHOW_CREATE_RESET";

export const SHOW_ADD_REVIEW_REQUEST = "SHOW_ADD_REVIEW_REQUEST";
export const SHOW_ADD_REVIEW_SUCCESS = "SHOW_ADD_REVIEW_SUCCESS";
export const SHOW_ADD_REVIEW_FAIL = "SHOW_ADD_REVIEW_FAIL";
export const SHOW_ADD_REVIEW_RESET = "SHOW_ADD_REVIEW_RESET";

export const SHOW_VENUE_PERFORMANCES_REQUEST =
  "SHOW_VENUE_PERFORMANCES_REQUEST";
export const SHOW_VENUE_PERFORMANCES_SUCCESS =
  "SHOW_VENUE_PERFORMANCES_SUCCESS";
export const SHOW_VENUE_PERFORMANCES_FAIL = "SHOW_VENUE_PERFORMANCES_FAIL";
export const SHOW_VENUE_PERFORMANCES_RESET = "SHOW_VENUE_PERFORMANCES_RESET";

export const SHOW_ADD_PERFORMANCE_REQUEST = "SHOW_ADD_PERFORMANCE_REQUEST";
export const SHOW_ADD_PERFORMANCE_SUCCESS = "SHOW_ADD_PERFORMANCES_SUCCESS";
export const SHOW_ADD_PERFORMANCE_FAIL = "SHOW_ADD_PERFORMANCE_FAIL";
export const SHOW_ADD_PERFORMANCE_RESET = "SHOW_ADD_PERFORMANCE_RESET";
