export const VENUE_LIST_REQUEST = "VENUE_LIST_REQUEST";
export const VENUE_LIST_SUCCESS = "VENUE_LIST_SUCCESS";
export const VENUE_LIST_FAIL = "VENUE_LIST_FAIL";
export const VENUE_LIST_UPDATE_REQUEST = "VENUE_LIST_UPDATE_REQUEST";

export const VENUE_DETAILS_REQUEST = "VENUE_DETAILS_REQUEST";
export const VENUE_DETAILS_SUCCESS = "VENUE_DETAILS_SUCCESS";
export const VENUE_DETAILS_FAIL = "VENUE_DETAILS_FAIL";
