export const VENUE_LIST_REQUEST = "VENUE_LIST_REQUEST";
export const VENUE_LIST_SUCCESS = "VENUE_LIST_SUCCESS";
export const VENUE_LIST_FAIL = "VENUE_LIST_FAIL";
export const VENUE_LIST_UPDATE_REQUEST = "VENUE_LIST_UPDATE_REQUEST";
export const VENUE_LIST_RESET = "VENUE_LIST_RESET";

export const VENUE_DETAILS_REQUEST = "VENUE_DETAILS_REQUEST";
export const VENUE_DETAILS_SUCCESS = "VENUE_DETAILS_SUCCESS";
export const VENUE_DETAILS_FAIL = "VENUE_DETAILS_FAIL";

export const VENUE_CREATE_REQUEST = "VENUE_CREATE_REQUEST";
export const VENUE_CREATE_SUCCESS = "VENUE_CREATE_SUCCESS";
export const VENUE_CREATE_FAIL = "VENUE_CREATE_FAIL";
export const VENUE_CREATE_RESET = "VENUE_CREATE_RESET";

export const VENUE_ADD_REVIEW_REQUEST = "VENUE_ADD_REVIEW_REQUEST";
export const VENUE_ADD_REVIEW_SUCCESS = "VENUE_ADD_REVIEW_SUCCESS";
export const VENUE_ADD_REVIEW_FAIL = "VENUE_ADD_REVIEW_FAIL";
export const VENUE_ADD_REVIEW_RESET = "VENUE_ADD_REVIEW_RESET";

export const VENUE_ADD_IMAGE_REQUEST = "VENUE_ADD_IMAGE_REQUEST";
export const VENUE_ADD_IMAGE_SUCCESS = "VENUE_ADD_IMAGE_SUCCESS";
export const VENUE_ADD_IMAGE_FAIL = "VENUE_ADD_IMAGE_FAIL";
export const VENUE_ADD_IMAGE_RESET = "VENUE_ADD_IMAGE_RESET";

export const VENUE_MY_REVIEWS_REQUEST = "VENUE_MY_REVIEWS_REQUEST";
export const VENUE_MY_REVIEWS_SUCCESS = "VENUE_MY_REVIEWS_SUCCESS";
export const VENUE_MY_REVIEWS_FAIL = "VENUE_MY_REVIEWS_FAIL";
export const VENUE_MY_REVIEWS_RESET = "VENUE_MY_REVIEWS_RESET";

export const VENUE_USER_REVIEWS_REQUEST = "VENUE_USER_REVIEWS_REQUEST";
export const VENUE_USER_REVIEWS_SUCCESS = "VENUE_USER_REVIEWS_SUCCESS";
export const VENUE_USER_REVIEWS_FAIL = "VENUE_USER_REVIEWS_FAIL";
export const VENUE_USER_REVIEWS_RESET = "VENUE_USER_REVIEWS_RESET";

export const VENUE_REVIEW_DETAILS_REQUEST = "VENUE_REVIEW_DETAILS_REQUEST";
export const VENUE_REVIEW_DETAILS_SUCCESS = "VENUE_REVIEW_DETAILS_SUCCESS";
export const VENUE_REVIEW_DETAILS_FAIL = "VENUE_REVIEW_DETAILS_FAIL";
export const VENUE_REVIEW_DETAILS_RESET = "VENUE_REVIEW_DETAILS_RESET";

export const VENUE_UPDATE_REVIEW_REQUEST = "VENUE_UPDATE_REVIEW_REQUEST";
export const VENUE_UPDATE_REVIEW_SUCCESS = "VENUE_UPDATE_REVIEW_SUCCESS";
export const VENUE_UPDATE_REVIEW_FAIL = "VENUE_UPDATE_REVIEW_FAIL";
export const VENUE_UPDATE_REVIEW_RESET = "VENUE_UPDATE_REVIEW_RESET";

export const VENUE_DELETE_REVIEW_REQUEST = "VENUE_DELETE_REVIEW_REQUEST";
export const VENUE_DELETE_REVIEW_SUCCESS = "VENUE_DELETE_REVIEW_SUCCESS";
export const VENUE_DELETE_REVIEW_FAIL = "VENUE_DELETE_REVIEW_FAIL";
export const VENUE_DELETE_REVIEW_RESET = "VENUE_DELETE_REVIEW_RESET";

export const VENUE_ADD_REVIEW_COMMENT_REQUEST =
  "VENUE_ADD_REVIEW_COMMENT_REQUEST";
export const VENUE_ADD_REVIEW_COMMENT_SUCCESS =
  "VENUE_ADD_REVIEW_COMMENT_SUCCESS";
export const VENUE_ADD_REVIEW_COMMENT_FAIL = "VENUE_ADD_REVIEW_COMMENT_FAIL";
export const VENUE_ADD_REVIEW_COMMENT_RESET = "VENUE_ADD_REVIEW_COMMENT_RESET";
